### ISSUE TITLE
authentification issue

### ISSUE THREAD

**Issue by seblemaguer** [cmusphinx/voice-ac-irina#2]
The access to the voice fails with an 401 error as it requires an authenfication to acess to the page.

**Comment by nshmyrev** [comment]
Which URL causes 401 please? It should be fixed now. Please reopen if not!

**Comment by seblemaguer** [comment]
This one:  'https://alphacephei.com/test/tts/ac_ru_irina_clunits-0.6.xml'

**Comment by nshmyrev** [comment]
@seblemaguer sorry about that, and where this xml file comes from? We only have

https://alphacephei.com/tts/ac_ru_irina_clunits-0.6.tar.bz2

no xml file

**Comment by seblemaguer** [comment]
Thanks, problem is solved. The ivy layout was just completely wrong but I didn't see it before you pasted the URL :)

Thanks a lot.
